version: 0.2

env:
  variables:
    S3_BUCKET: "cicdbucket-3601"

phases: 
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing NPM dependencies..."
      - pip install -r lambda/requirements.txt -t lambda/
    build:
      commands:
        - echo "Building lambda project..."
        - cd lambda
        - zip -r ../lambda.zip .
        - cd ..
    post_build:
      commands:
        - echo "Uploading to S3..."
        - aws s3 cp lambda.zip s3://$S3_BUCKET/lambda.zip
        - echo "Build completed."
artifacts:
  files:
    - lambda.zip
    - cloudformation/**