AWSTemplateFormatVersion: '2010-09-09'
Description: Creating EC2 instance with Lambda and Role Stack

Resources:
  IAMRolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cicdbucket-3601.s3.us-east-1.amazonaws.com/roles.yml

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cicdbucket-3601.s3.us-east-1.amazonaws.com/lambda-deploy.yml

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0c02fb55956c7d316
      InstanceType: t3.micro
      KeyName: raj-key-us
      SecurityGroups:
        - !Ref CiCdPipelineSG
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "Welcome to the Static Frontend on EC2!" > /var/www/html/index.html

  CiCdPipelineSG: 
    Type: AWS::EC2::SecurityGroup 
    Properties: 
      GroupDescription: Enable HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          